language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

go:
  - 1.17.x

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ancientlore/goimg:${TRAVIS_TAG:-latest} .
  - docker build -t test -f Dockerfile.test .
  - docker run -it --rm test
  - docker push ancientlore/goimg:${TRAVIS_TAG:-latest}
