services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ancientlore/goimg:${TRAVIS_TAG:-latest} .
  - docker push ancientlore/goimg:${TRAVIS_TAG:-latest}
