language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

go:
  - 1.16.x

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ancientlore/goimg:${TRAVIS_TAG:-latest} .
  - docker push ancientlore/goimg:${TRAVIS_TAG:-latest}
