language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

go:
  - 1.17.x

script:
  - GO_VERSION=$(go env GOVERSION | sed s/^go//)
  - GO_MAJOR_VERSION=$(go env GOVERSION | sed s/^go// | sed -r 's/^([0-9]+\.[0-9]+)(\.[0-9]+)?$/\1/')
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg "GO_VERSION=${GO_VERSION}" -t ancientlore/goimg:${TRAVIS_TAG:-latest} .
  - docker tag ancientlore/goimg:${TRAVIS_TAG:-latest} ancientlore/goimg:${GO_VERSION}
  - docker tag ancientlore/goimg:${TRAVIS_TAG:-latest} ancientlore/goimg:${GO_MAJOR_VERSION}
  - docker build --build-arg "GO_VERSION=${GO_VERSION}" -t test -f Dockerfile.test .
  - docker run -it --rm test
  - docker push ancientlore/goimg:${TRAVIS_TAG:-latest}
  - docker push ancientlore/goimg:${GO_VERSION}
  - docker push ancientlore/goimg:${GO_MAJOR_VERSION}
