ARG GO_VERSION=1.23

FROM golang:${GO_VERSION} AS builder
COPY . /go/test
WORKDIR /go/test
RUN CGO_ENABLED=0 go build -o /go/bin/test

FROM goimg:${GO_VERSION}
COPY --from=builder /go/bin/test /usr/bin/test
CMD [ "/usr/bin/test"]
